name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write        # for test results
  pull-requests: write # for test results

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Set up SBT
      uses: sbt/setup-sbt@v1

    - name: Run tests
      # We exclude "CPU" tests which require more memory than is available
      run: sbt 'testOnly -- -l "org.scalatest.tags.CPU"'

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          target/test-reports/*.xml
